# Generated by Django 2.1.1 on 2019-01-02 14:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='app1/photos/')),
                ('services', models.TextField()),
                ('tags', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='app1/photos/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='app1/photos/')),
                ('menu', models.TextField()),
                ('tags', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('DistAddress', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='app1/photos/')),
                ('Comment', models.TextField()),
                ('tags', models.CharField(max_length=200)),
                ('DepartureDate', models.DateTimeField()),
                ('ReturnDate', models.DateTimeField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('galaryPictures', models.ManyToManyField(blank=True, null=True, to='app1.Pictures')),
                ('registeredUsers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='app1/photos/')),
                ('comment', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('serchArea', models.CharField(blank=True, max_length=600, null=True)),
                ('galaryPictures', models.ManyToManyField(blank=True, null=True, to='app1.Pictures')),
            ],
        ),
        migrations.CreateModel(
            name='villaCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=1000)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='villaDateStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusId', models.IntegerField(choices=[(1, 'اجاره شده'), (2, 'رزرو شده'), (3, 'دردست تعمیر'), (4, 'آزاد'), (5, 'اجاره داده نمی شود')], default=1)),
                ('date', models.DateTimeField()),
                ('jdateYear', models.IntegerField(blank=True, null=True)),
                ('jdateMonth', models.IntegerField(blank=True, null=True)),
                ('jdateDay', models.IntegerField(blank=True, null=True)),
                ('villaId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Villa')),
            ],
        ),
        migrations.CreateModel(
            name='villaStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('j_fromDateYear', models.IntegerField(default=1397, validators=[django.core.validators.MaxValueValidator(1400), django.core.validators.MinValueValidator(1397)], verbose_name='از سال: ')),
                ('j_fromDateMonth', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='از ماه: ')),
                ('j_fromDateDay', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)], verbose_name='از روز: ')),
                ('j_toDateYear', models.IntegerField(default=1397, validators=[django.core.validators.MaxValueValidator(1400), django.core.validators.MinValueValidator(1397)], verbose_name='تا سال: ')),
                ('j_toDateMonth', models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='تا ماه: ')),
                ('j_toDateDay', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)], verbose_name='تا روز: ')),
                ('STATUS_OF_VILLA', models.IntegerField(choices=[(1, 'اجاره شده'), (2, 'رزرو شده'), (3, 'دردست تعمیر'), (4, 'آزاد'), (5, 'اجاره داده نمی شود')], default=1)),
                ('fromDate', models.DateTimeField(blank=True, null=True)),
                ('toDate', models.DateTimeField(blank=True, null=True)),
                ('villa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Villa')),
            ],
        ),
        migrations.AddField(
            model_name='villa',
            name='villaCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.villaCategory'),
        ),
    ]
