# Generated by Django 2.1.1 on 2019-01-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='villa',
            options={'ordering': ('pub_date',)},
        ),
    ]
