# Generated by Django 2.1.1 on 2019-01-03 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='villadatestatus',
            options={'ordering': ('villaId', 'date')},
        ),
        migrations.AlterField(
            model_name='villadatestatus',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='villadatestatus',
            name='jdateWeekDay',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
