# Generated by Django 2.1.1 on 2018-12-31 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_villadatestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='villadatestatus',
            name='statusId',
            field=models.IntegerField(choices=[(1, 'اجاره شده'), (2, 'رزرو شده'), (3, 'دردست تعمیر'), (4, 'آزاد'), (5, 'اجاره داده نمی شود')], default=1),
        ),
        migrations.AddField(
            model_name='villadatestatus',
            name='villaId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Villa'),
        ),
    ]
