# Generated by Django 2.1.1 on 2019-01-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20190107_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villa',
            name='avgPrice',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='villa',
            name='maxPrice',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='villa',
            name='minPrice',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
