# Generated by Django 2.1.1 on 2019-01-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20190103_0709'),
    ]

    operations = [
        migrations.AddField(
            model_name='villadatestatus',
            name='statusTitle',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
