# Generated by Django 2.1.1 on 2018-10-23 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0002_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='writer',
        ),
        migrations.AddField(
            model_name='tour',
            name='registeredUsers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
