# Generated by Django 2.1.1 on 2019-01-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_villadatestatus_statustitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villadatestatus',
            name='statusTitle',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
