# Generated by Django 2.1.1 on 2019-01-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20190108_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villadatestatus',
            name='statusId',
            field=models.IntegerField(choices=[(0, 'آزاد'), (1, 'اجاره شده'), (2, 'رزرو شده'), (3, 'دردست تعمیر'), (4, 'اجاره داده نمی شود')], default=0),
        ),
        migrations.AlterField(
            model_name='villastatus',
            name='STATUS_OF_VILLA',
            field=models.IntegerField(choices=[(0, 'آزاد'), (1, 'اجاره شده'), (2, 'رزرو شده'), (3, 'دردست تعمیر'), (4, 'اجاره داده نمی شود')], default=0),
        ),
    ]
