# Generated by Django 2.1.1 on 2018-10-23 09:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0003_auto_20181023_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='registeredUsers',
        ),
        migrations.AddField(
            model_name='tour',
            name='registeredUsers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
