# Generated by Django 2.1.1 on 2019-01-06 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20190106_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villadatestatus',
            name='statusTitle',
        ),
    ]
