# Generated by Django 2.1.1 on 2018-11-17 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='app1/photos/')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='tour',
            name='registeredUsers',
            field=models.ManyToManyField(to='app1.Pictures'),
        ),
    ]
