# Generated by Django 2.1.1 on 2019-01-23 14:48

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20190122_1356'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='villastatus',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=0, default=Decimal('0.0'), default_currency='IRR', max_digits=14, verbose_name='قیمت'),
        ),
    ]
