# Generated by Django 2.1.1 on 2019-01-27 08:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20190123_0648'),
    ]

    operations = [
        
        migrations.AddField(
            model_name='villavote',
            name='ownerTitle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        
    ]
