# Generated by Django 2.1.1 on 2018-11-17 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_remove_tour_galarypictures'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pictures',
        ),
    ]
