# Generated by Django 2.1.1 on 2019-01-29 10:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20190127_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictures',
            old_name='title',
            new_name='PictureTitle',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='title',
            new_name='TourTitle',
        ),
        migrations.RenameField(
            model_name='villa',
            old_name='title',
            new_name='VillaTitle',
        ),
        migrations.RenameField(
            model_name='villacategory',
            old_name='title',
            new_name='villaCategoryTitle',
        ),

    ]
