# Generated by Django 2.1.1 on 2019-01-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_auto_20190129_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictures',
            old_name='PictureTitle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='TourTitle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='villa',
            old_name='VillaTitle',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='villacategory',
            old_name='villaCategoryTitle',
            new_name='title',
        ),
    ]
