# Generated by Django 2.1.1 on 2018-11-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_pictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='galaryPictures',
            field=models.ManyToManyField(to='app1.Pictures'),
        ),
    ]
