# Generated by Django 2.1.1 on 2018-11-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_tour_galarypictures'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='color',
            field=models.CharField(default='red', max_length=7),
        ),
    ]
