# Generated by Django 2.1.1 on 2018-11-26 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_tour_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Villa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='app1/photos/')),
                ('comment', models.TextField()),
                ('tags', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('galaryPictures', models.ManyToManyField(to='app1.Pictures')),
            ],
        ),
        migrations.RemoveField(
            model_name='tour',
            name='color',
        ),
    ]
