# Generated by Django 2.1.1 on 2019-02-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_villastatus_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='costumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('address', models.TextField(blank=True, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True)),
                ('firstname', models.CharField(blank=True, max_length=100, null=True)),
                ('lastname', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.IntegerField(choices=[(0, 'غیرفعال'), (1, 'فعال')], default=1)),
            ],
            options={
                'verbose_name': 'مشتری',
            },
        ),
    ]
