# Generated by Django 2.1.1 on 2018-12-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_auto_20181201_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='villaCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=1000)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='villa',
            name='tags',
        ),
    ]
