# Generated by Django 2.1.5 on 2019-02-09 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_costumer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='costumer',
            new_name='customer',
        ),
    ]
