# Generated by Django 2.1.5 on 2019-02-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20190209_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'مشتری'},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'verbose_name_plural': 'هتل'},
        ),
        migrations.AlterModelOptions(
            name='pictures',
            options={'verbose_name_plural': 'عکس'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'verbose_name_plural': 'رستوران'},
        ),
        migrations.AlterModelOptions(
            name='tour',
            options={'verbose_name_plural': 'تور'},
        ),
        migrations.AlterModelOptions(
            name='villa',
            options={'ordering': ('-pub_date',), 'verbose_name_plural': 'ویلا'},
        ),
        migrations.AlterModelOptions(
            name='villacategory',
            options={'verbose_name_plural': 'دسته بندی ویلا'},
        ),
        migrations.AlterModelOptions(
            name='villastatus',
            options={'verbose_name_plural': 'وضعیت ویلا'},
        ),
        migrations.AlterModelOptions(
            name='villavote',
            options={'verbose_name_plural': 'نظرات ویلا'},
        ),
        migrations.AddField(
            model_name='villa',
            name='latitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='longitude',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
