# Generated by Django 2.1.1 on 2018-12-02 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20181202_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='villaCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.villaCategory'),
        ),
    ]
