# Generated by Django 2.1.1 on 2018-12-02 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0018_auto_20181202_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tour',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='villa',
            old_name='Title',
            new_name='title',
        ),
    ]
