# Generated by Django 2.1.1 on 2018-12-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0019_auto_20181202_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='villa',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='villacategory',
            old_name='title',
            new_name='Title',
        ),
    ]
