# Generated by Django 2.1.1 on 2018-12-02 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_auto_20181202_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictures',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='villa',
            old_name='Title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='villacategory',
            old_name='Title',
            new_name='title',
        ),
    ]
