# Generated by Django 2.1.1 on 2018-12-02 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_remove_villa_galarypictures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='writer',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='galaryPictures',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='registeredUsers',
        ),
    ]
