# Generated by Django 2.1.1 on 2018-12-03 13:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0023_auto_20181202_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='galaryPictures',
            field=models.ManyToManyField(to='app1.Pictures'),
        ),
        migrations.AddField(
            model_name='tour',
            name='registeredUsers',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='villa',
            name='galaryPictures',
            field=models.ManyToManyField(to='app1.Pictures'),
        ),
        migrations.AddField(
            model_name='villa',
            name='villaCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.villaCategory'),
        ),
    ]
