# Generated by Django 2.1.1 on 2018-12-09 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_rentvilla'),
    ]

    operations = [
        migrations.CreateModel(
            name='villaStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('rentDate', models.DateTimeField()),
                ('year_in_school', models.CharField(choices=[('RENTED', 'Rented'), ('RESERVED', 'Reserved'), ('FREE', 'Free'), ('MAINTENANCE', 'Maintenance')], default='RENTED', max_length=2)),
                ('villa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Villa')),
            ],
        ),
        migrations.RemoveField(
            model_name='rentvilla',
            name='villa',
        ),
        migrations.DeleteModel(
            name='rentVilla',
        ),
    ]
