# Generated by Django 2.1.1 on 2018-12-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0026_auto_20181209_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villastatus',
            name='rentDate',
        ),
        migrations.AddField(
            model_name='villastatus',
            name='fromDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villastatus',
            name='toDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
