# Generated by Django 2.1.1 on 2018-12-09 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0028_auto_20181209_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='villastatus',
            old_name='year_in_school',
            new_name='STATUS_OF_VILLA',
        ),
    ]
