# Generated by Django 2.1.1 on 2018-12-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0030_auto_20181209_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villastatus',
            name='STATUS_OF_VILLA',
            field=models.CharField(choices=[('RENTED', 'اجاره داده شده'), ('RESERVED', 'رزرو شده'), ('FREE', 'خالی'), ('MAINTENANCE', 'در دست تعمیر')], default='FREE', max_length=2),
        ),
    ]
