# Generated by Django 2.1.1 on 2018-12-15 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0032_auto_20181209_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='Latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='Longitude',
            field=models.FloatField(null=True),
        ),
    ]
