# Generated by Django 2.1.1 on 2018-12-15 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0033_auto_20181215_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villastatus',
            name='STATUS_OF_VILLA',
        ),
    ]
