# Generated by Django 2.1.1 on 2018-12-15 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0035_villastatus_status_of_villa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villa',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='Longitude',
        ),
    ]
