# Generated by Django 2.1.1 on 2018-12-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0036_auto_20181215_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='Latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='Longitude',
            field=models.FloatField(null=True),
        ),
    ]
