# Generated by Django 2.1.1 on 2018-12-15 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0037_auto_20181215_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villastatus',
            name='villa',
        ),
    ]
