# Generated by Django 2.1.1 on 2018-12-15 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0038_remove_villastatus_villa'),
    ]

    operations = [
        migrations.AddField(
            model_name='villastatus',
            name='villa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.Villa'),
        ),
    ]
