# Generated by Django 2.1.1 on 2018-12-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0039_villastatus_villa'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='addressArea',
            field=models.CharField(max_length=600, null=True),
        ),
    ]
