# Generated by Django 2.1.1 on 2018-12-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0040_villa_addressarea'),
    ]

    operations = [
        migrations.RenameField(
            model_name='villa',
            old_name='addressArea',
            new_name='pwrioID',
        ),
    ]
