# Generated by Django 2.1.1 on 2018-12-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0042_villa_sercharea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villastatus',
            name='STATUS_OF_VILLA',
            field=models.IntegerField(choices=[(1, 'اجاره شده'), (2, 'رزرو شده'), (3, 'دردست تعمیر'), (4, 'آزاد'), (5, 'اجاره داده نمی شود')], default=1),
        ),
    ]
