# Generated by Django 2.1.1 on 2018-12-18 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0043_auto_20181216_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villa',
            name='pwrioID',
        ),
        migrations.AlterField(
            model_name='villa',
            name='Latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='villa',
            name='Longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='villa',
            name='serchArea',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
