# Generated by Django 2.1.1 on 2018-12-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0044_auto_20181218_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villa',
            name='galaryPictures',
            field=models.ManyToManyField(blank=True, null=True, to='app1.Pictures'),
        ),
    ]
