# Generated by Django 2.1.1 on 2018-12-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0045_auto_20181221_0721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villa',
            name='Latitude',
        ),
        migrations.RemoveField(
            model_name='villa',
            name='Longitude',
        ),
    ]
