# Generated by Django 2.1.1 on 2018-12-21 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0048_auto_20181221_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='Latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='villa',
            name='Longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
