# Generated by Django 2.1.1 on 2018-12-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0049_auto_20181221_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='villa',
            name='room',
            field=models.TextField(blank=True, null=True),
        ),
    ]
