# Generated by Django 2.1.1 on 2018-12-21 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0050_villa_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villa',
            name='room',
        ),
    ]
