# Generated by Django 2.1.1 on 2018-12-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0052_auto_20181221_0754'),
    ]

    operations = [
        migrations.AddField(
            model_name='villastatus',
            name='j_fromDate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='از تاریخ: '),
        ),
        migrations.AddField(
            model_name='villastatus',
            name='j_toDate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='تا تاریخ: '),
        ),
    ]
