# Generated by Django 2.1.1 on 2018-12-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0053_auto_20181224_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villastatus',
            name='j_fromDate',
        ),
        migrations.RemoveField(
            model_name='villastatus',
            name='j_toDate',
        ),
        migrations.AddField(
            model_name='villastatus',
            name='j_fromDateDay',
            field=models.IntegerField(default=1, verbose_name='از روز: '),
        ),
        migrations.AddField(
            model_name='villastatus',
            name='j_fromDateMonth',
            field=models.IntegerField(default=1, verbose_name='از ماه: '),
        ),
        migrations.AddField(
            model_name='villastatus',
            name='j_fromDateYear',
            field=models.IntegerField(default=1397, verbose_name='از سال: '),
        ),
        migrations.AddField(
            model_name='villastatus',
            name='j_toDateDay',
            field=models.IntegerField(default=1, verbose_name='تا روز: '),
        ),
        migrations.AddField(
            model_name='villastatus',
            name='j_toDateMonth',
            field=models.IntegerField(default=1, verbose_name='تا ماه: '),
        ),
        migrations.AddField(
            model_name='villastatus',
            name='j_toDateYear',
            field=models.IntegerField(default=1397, verbose_name='تا سال: '),
        ),
    ]
