# Generated by Django 2.1.1 on 2018-12-24 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0055_auto_20181224_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='villastatus',
            name='j_fromDateDay',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)], verbose_name='از روز: '),
        ),
        migrations.AlterField(
            model_name='villastatus',
            name='j_fromDateMonth',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='از ماه: '),
        ),
        migrations.AlterField(
            model_name='villastatus',
            name='j_fromDateYear',
            field=models.IntegerField(default=1397, validators=[django.core.validators.MaxValueValidator(1400), django.core.validators.MinValueValidator(1397)], verbose_name='از سال: '),
        ),
        migrations.AlterField(
            model_name='villastatus',
            name='j_toDateDay',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(31), django.core.validators.MinValueValidator(1)], verbose_name='تا روز: '),
        ),
        migrations.AlterField(
            model_name='villastatus',
            name='j_toDateMonth',
            field=models.IntegerField(default=10, validators=[django.core.validators.MaxValueValidator(12), django.core.validators.MinValueValidator(1)], verbose_name='تا ماه: '),
        ),
        migrations.AlterField(
            model_name='villastatus',
            name='j_toDateYear',
            field=models.IntegerField(default=1397, validators=[django.core.validators.MaxValueValidator(1400), django.core.validators.MinValueValidator(1397)], verbose_name='تا سال: '),
        ),
    ]
