# Generated by Django 2.1.1 on 2018-12-28 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0058_auto_20181228_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='villadatestatus',
            name='jdate',
        ),
    ]
